services:
  - type: web
    name: my-fastapi-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: TAVILY_API_KEY
        value: "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"
      - key: GEMINI_API_KEY
        value: "AIzaSyCIHEdKAX7VfQmp6o3_Kl3gxpdgJU-Tik4"
    autoDeploy: true
    region: oregon  # Choose your preferred region
